version: "3"

services:
  ###> doctrine/doctrine-bundle ###

  database:
    build:
      context: .php/
      dockerfile: Dockerfile
    container_name: debara
    image: docker.io/guidestone83/debaras-dev-prod
    environment:
      MYSQL_DATABASE: debara
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      DATABASE_URL: mysql://root:root@database:3305/debara
      #DATABASE_URL: mysql://root:@127.0.0.1:3306/debara?serverVersion=10.4.28-MariaDB&charset=utf8mb4
    volumes:
      - ./.data/db:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ###< doctrine/doctrine-bundle ###
    ports:
      - 3305:3305

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

