version: "3"

services:
  ###> doctrine/doctrine-bundle ###

  database:
    build:
      context: .php/
      dockerfile: Dockerfile
    container_name: debara
    image: sha256:45cd4e8d3b7100e3dc34c95632088ad3bcc382e647d3e0a9ca992ff983ad7f04
    environment:
      MYSQL_DATABASE: debara
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - ./.data/db:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ###< doctrine/doctrine-bundle ###
    ports:
      - 3305:3305

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
